In [17]:
import numpy as np
import pandas as pd

In [18]:
#Loading Data
dataset = pd.read_csv("./drive/MyDrive/Machine Learning/Data Preprocessing/data/data.csv")
print(dataset)

         City   Age   Salary Eligilbe for bonus
0      Mumbai  27.0  51000.0                Yes
1     NewYork  27.0  48000.0                Yes
2      Mumbai  30.0  52000.0                 No
3     NewYork   NaN  66000.0                 No
4       Tokyo  48.0      NaN                Yes
5       Tokyo   NaN  51000.0                 No
6   Singapore  33.0  69000.0                 No
7     NewYork  40.0  79000.0                Yes
8   Singapore  35.0  72000.0                 No
9     NewYork  45.0  79000.0                Yes
10     Mumbai  31.0  85000.0                Yes
11  Singapore  37.0  49000.0                 No

In [19]:
#Create dependent & independent variable vectors
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[['Mumbai' 27.0 51000.0]
 ['NewYork' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['NewYork' nan 66000.0]
 ['Tokyo' 48.0 nan]
 ['Tokyo' nan 51000.0]
 ['Singapore' 33.0 69000.0]
 ['NewYork' 40.0 79000.0]
 ['Singapore' 35.0 72000.0]
 ['NewYork' 45.0 79000.0]
 ['Mumbai' 31.0 85000.0]
 ['Singapore' 37.0 49000.0]]
['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'Yes' 'No']

In [20]:
#Handle missing data
#Count the number of missing vlues in each column
# print(dataset.isnull().sum())

# 1.Drop the records
dataset.dropna(inplace=True)
# print(dataset)

# 2.Replace the missing values
print(x, '\n')
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

         City   Age   Salary Eligilbe for bonus
0      Mumbai  27.0  51000.0                Yes
1     NewYork  27.0  48000.0                Yes
2      Mumbai  30.0  52000.0                 No
6   Singapore  33.0  69000.0                 No
7     NewYork  40.0  79000.0                Yes
8   Singapore  35.0  72000.0                 No
9     NewYork  45.0  79000.0                Yes
10     Mumbai  31.0  85000.0                Yes
11  Singapore  37.0  49000.0                 No

In [21]:
# Data Encoding
# Handle/Encode categorical data
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_encoder = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(column_encoder.fit_transform(x))
print(x, '\n')

# Label Encoding
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
print(y)

[[1.0 0.0 0.0 0.0 27.0 51000.0]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 30.0 52000.0]
 [0.0 1.0 0.0 0.0 nan 66000.0]
 [0.0 0.0 0.0 1.0 48.0 nan]
 [0.0 0.0 0.0 1.0 nan 51000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]
 [0.0 1.0 0.0 0.0 40.0 79000.0]
 [0.0 0.0 1.0 0.0 35.0 72000.0]
 [0.0 1.0 0.0 0.0 45.0 79000.0]
 [1.0 0.0 0.0 0.0 31.0 85000.0]
 [0.0 0.0 1.0 0.0 37.0 49000.0]]

[1 1 0 0 1 0 0 1 0 1 1 0]

In [22]:
# Split the dataset for training & testing
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=9)
print(x_train, y_train, '\n')
print(x_test, y_test)

[[1.0 0.0 0.0 0.0 27.0 51000.0]
 [0.0 1.0 0.0 0.0 nan 66000.0]
 [0.0 0.0 0.0 1.0 48.0 nan]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 37.0 49000.0]
 [1.0 0.0 0.0 0.0 31.0 85000.0]
 [0.0 0.0 1.0 0.0 35.0 72000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]
 [0.0 0.0 0.0 1.0 nan 51000.0]] [1 0 1 1 0 1 0 0 0]

[[0.0 1.0 0.0 0.0 40.0 79000.0]
 [0.0 1.0 0.0 0.0 45.0 79000.0]
 [1.0 0.0 0.0 0.0 30.0 52000.0]] [1 1 0]

In [23]:
# Feature Scaling - Standardiztion & Normalization
# Scaling everything to the same range

# Standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train[:, 4:] = scaler.fit_transform(x_train[:, 4:])
x_test[:, 4:] = scaler.fit_transform(x_test[:, 4:])
print(x_train, '\n')
print(x_test)

[[1.0 0.0 0.0 0.0 -1.0451586902944878 -0.8145479694229155]
 [0.0 1.0 0.0 0.0 nan 0.3631117454053961]
 [0.0 0.0 0.0 1.0 2.0903173805889756 nan]
 [0.0 1.0 0.0 0.0 -1.0451586902944878 -1.0500799123885778]
 [0.0 0.0 1.0 0.0 0.44792515298335195 -0.9715692647333571]
 [1.0 0.0 0.0 0.0 -0.44792515298335195 1.854814050854591]
 [0.0 0.0 1.0 0.0 0.14930838432778398 0.8341756313367208]
 [0.0 0.0 1.0 0.0 -0.14930838432778398 0.5986436883710584]
 [0.0 0.0 0.0 1.0 nan -0.8145479694229155]]

[[0.0 1.0 0.0 0.0 0.26726124191242395 0.7071067811865476]
 [0.0 1.0 0.0 0.0 1.0690449676496971 0.7071067811865476]
 [1.0 0.0 0.0 0.0 -1.336306209562122 -1.4142135623730951]]